apiVersion: community.io/v1alpha1
kind: Weekly
metadata:
  name: weekly-1
spec:
  weekly_name: "Kubernetes Weekly #1"
  weekly_date: 10/10/2020
  community_name: Cloud Native Indonesia Community
  tags:
    - kubeweekly
    - cncf
  image_url: https://avatars2.githubusercontent.com/u/11990726?s=460&u=824968339d334d44195b6ec544adb192de60f06a&v=4
  articles:
  - title: Kubernetes 1
    url: http://kubernetes.io/
    type: Article
  - title: Kubernetes 1
    url: http://kubernetes.io/
    type: News
  - title: OpenShift 1
    url: http://kubernetes.io/
    type: News
  - title: Kubernetes 1
    url: http://kubernetes.io/
    type: Article
