---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: weeklies.community.io
spec:
  group: community.io
  names:
    kind: Weekly
    listKind: WeeklyList
    plural: weeklies
    singular: weekly
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Weekly is the Schema for the weeklies API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WeeklySpec defines the desired state of Weekly
          properties:
            articles:
              items:
                properties:
                  title:
                    type: string
                  type:
                    type: string
                  url:
                    type: string
                required:
                - title
                - type
                - url
                type: object
              type: array
            community:
              type: string
            date:
              type: string
            image:
              type: string
            name:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            tags:
              items:
                type: string
              type: array
          required:
          - articles
          - community
          - date
          - image
          - name
          - tags
          type: object
        status:
          description: WeeklyStatus defines the observed state of Weekly
          properties:
            send:
              type: boolean
          required:
          - send
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meetups.community.io
spec:
  group: community.io
  names:
    kind: Meetup
    listKind: MeetupList
    plural: meetups
    singular: meetup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Meetup is the Schema for the meetups API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MeetupSpec defines the desired state of Meetup
          properties:
            city:
              type: string
            date:
              type: string
            image:
              type: string
            name:
              type: string
            place:
              type: string
            registration_url:
              type: string
            speakers:
              items:
                properties:
                  company:
                    type: string
                  name:
                    type: string
                  position:
                    type: string
                  title:
                    type: string
                required:
                - company
                - name
                - position
                - title
                type: object
              type: array
            sponsor:
              type: string
            tags:
              items:
                type: string
              type: array
            time:
              type: string
          required:
          - city
          - date
          - image
          - name
          - place
          - registration_url
          - speakers
          - sponsor
          - tags
          - time
          type: object
        status:
          description: MeetupStatus defines the observed state of Meetup
          properties:
            send:
              type: boolean
          required:
          - send
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: announcements.community.io
spec:
  group: community.io
  names:
    kind: Announcement
    listKind: AnnouncementList
    plural: announcements
    singular: announcement
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Announcement is the Schema for the announcements API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AnnouncementSpec defines the desired state of Announcement
          properties:
            community:
              type: string
            image:
              type: string
            message:
              type: string
            tags:
              items:
                type: string
              type: array
            title:
              type: string
          required:
          - community
          - image
          - message
          - tags
          - title
          type: object
        status:
          description: AnnouncementStatus defines the observed state of Announcement
          properties:
            send:
              type: boolean
          required:
          - send
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
