---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
data:
  TELEGRAM_ENABLED: {{ .Values.telegram.enabled | b64enc }}
  TELEGRAM_TOKEN: {{ .Values.telegram.token | b64enc }}
  TELEGRAM_CHATID: {{ .Values.telegram.chatid | b64enc }}
  TWITTER_ENABLED: {{ .Values.twitter.enabled | b64enc }}
  TWITTER_API_KEY: {{ .Values.twitter.api_key | b64enc }}
  TWITTER_API_SECRET_KEY: {{ .Values.twitter.api_secret_key | b64enc }}
  TWITTER_ACCESS_TOKEN: {{ .Values.twitter.access_token | b64enc }}
  TWITTER_ACCESS_TOKEN_SECRET: {{ .Values.twitter.access_token_secret | b64enc }}
