apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: announcements.community.io
spec:
  group: community.io
  names:
    kind: Announcement
    listKind: AnnouncementList
    plural: announcements
    singular: announcement
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Announcement is the Schema for the announcements API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AnnouncementSpec defines the desired state of Announcement
          properties:
            community:
              type: string
            image:
              type: string
            message:
              type: string
            tags:
              items:
                type: string
              type: array
            title:
              type: string
          required:
          - community
          - image
          - message
          - tags
          - title
          type: object
        status:
          description: AnnouncementStatus defines the observed state of Announcement
          properties:
            send:
              type: boolean
          required:
          - send
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
