apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meetups.community.io
spec:
  group: community.io
  names:
    kind: Meetup
    listKind: MeetupList
    plural: meetups
    singular: meetup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Meetup is the Schema for the meetups API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MeetupSpec defines the desired state of Meetup
          properties:
            city:
              type: string
            date:
              type: string
            image:
              type: string
            name:
              type: string
            place:
              type: string
            registration_url:
              type: string
            speakers:
              items:
                properties:
                  company:
                    type: string
                  name:
                    type: string
                  position:
                    type: string
                  title:
                    type: string
                required:
                - company
                - name
                - position
                - title
                type: object
              type: array
            sponsor:
              type: string
            tags:
              items:
                type: string
              type: array
            time:
              type: string
          required:
          - city
          - date
          - image
          - name
          - place
          - registration_url
          - speakers
          - sponsor
          - tags
          - time
          type: object
        status:
          description: MeetupStatus defines the observed state of Meetup
          properties:
            send:
              type: boolean
          required:
          - send
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
