apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: weeklies.community.io
spec:
  group: community.io
  names:
    kind: Weekly
    listKind: WeeklyList
    plural: weeklies
    singular: weekly
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Weekly is the Schema for the weeklies API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WeeklySpec defines the desired state of Weekly
          properties:
            articles:
              items:
                properties:
                  title:
                    type: string
                  url:
                    type: string
                required:
                - title
                - url
                type: object
              type: array
            name:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          required:
          - articles
          - name
          type: object
        status:
          description: WeeklyStatus defines the observed state of Weekly
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
