---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  replicas: {{ .Values.operator.replica }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: community-operator
      containers:
      - name: {{ .Chart.Name }}-container
        image: {{ .Values.operator.image }}:{{ .Values.operator.tag }}
        imagePullPolicy: {{ .Values.operator.pullPolicy }}
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: {{ .Chart.Name }}
        volumeMounts:
        - name: {{ .Chart.Name }}-secret
          mountPath: "/etc/community-operator/config/"
      volumes:
      - name: {{ .Chart.Name }}-secret
        secret:
          secretName: {{ .Chart.Name }}-secret
          defaultMode: 0740
